graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    #exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphql.playground:
  mapping: /playground
  endpoint: /graphql
  cdn:
    enabled: true
    version: latest
